### ISSUE TITLE
Project specific settings

### ISSUE THREAD

**Issue by stonerl** [Aeron/isort.novaextension#2]
Could you add project specific settings? So one could have different isort settings for a project.

**Comment by Aeron** [comment]
There are project-specific settings already. It looks like the following:

<img width="605" alt="Screenshot 2023-09-18 at 22 33 46" src="https://github.com/Aeron/isort.novaextension/assets/278423/3851aa7d-5f2c-4ebc-a1d0-d803377c1810">

Do you have anything particular in mind that is missing maybe?

**Comment by stonerl** [comment]
😳 I must have been blind
